from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict
from typing import List
from typing import Set

import pandas as pd


COL_HS_CODE = "HS\uBD80\uD638"
COL_START_DATE = "\uC801\uC6A9\uC2DC\uC791\uC77C\uC790"
COL_END_DATE = "\uC801\uC6A9\uC885\uB8CC\uC77C\uC790"
COL_KO_NAME = "\uD55C\uAE00\uD488\uBAA9\uBA85"
COL_EN_NAME = "\uC601\uBB38\uD488\uBAA9\uBA85"
COL_WEIGHT_UNIT = "\uC911\uB7C9\uB2E8\uC704\uCF54\uB4DC"
COL_NATURE_CODE_NAME = "\uC131\uC9C8\uD1B5\uD569\uBD84\uB958\uCF54\uB4DC\uBA85"

COL_STANDARD_NAME = "\uD45C\uC900\uD488\uBA85_\uD55C\uAE00"
COL_REQUIRED_SPECS = "\uD544\uC218\uADDC\uACA9_\uD55C\uAE00"
COL_DETAIL_NOTES = "\uC138\uBD80\uBD84\uB958\uB0B4\uC6A9"


def normalize_text(value: object) -> str:
    if value is None:
        return ""
    text = str(value).strip()
    if not text or text.lower() == "nan":
        return ""
    return " ".join(text.split())


def normalize_code(value: object) -> str:
    raw = normalize_text(value)
    if not raw:
        return ""
    return "".join(ch for ch in raw if ch.isdigit())


def normalize_date(value: object) -> str:
    text = normalize_text(value)
    if not text:
        return ""
    if len(text) >= 10 and text[4] == "-" and text[7] == "-":
        return text[:10]

    digits = normalize_code(text)
    if len(digits) >= 8:
        return f"{digits[:4]}-{digits[4:6]}-{digits[6:8]}"

    parsed = pd.to_datetime(text, errors="coerce")
    if pd.isna(parsed):
        return text
    return parsed.strftime("%Y-%m-%d")


def normalize_nature_name(value: object) -> str:
    text = normalize_text(value)
    if len(text) >= 2 and text[0] == "(" and text[-1] == ")":
        return text[1:-1].strip()
    return text


def push_limited(target: Set[str], value: str, limit: int = 6) -> None:
    if not value:
        return
    if len(target) >= limit:
        return
    target.add(value)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build HS/HSK catalog from customs xlsx files.")
    parser.add_argument("--hs-file", required=True, help="Path to customs HS xlsx file")
    parser.add_argument("--standard-file", required=True, help="Path to customs standard-name xlsx file")
    parser.add_argument("--out-file", required=True, help="Output .ts file path")
    args = parser.parse_args()

    hs_path = Path(args.hs_file)
    standard_path = Path(args.standard_file)
    out_path = Path(args.out_file)

    hs_df = pd.read_excel(hs_path, dtype=str).fillna("")
    std_df = pd.read_excel(standard_path, dtype=str).fillna("")

    std_by_hsk: Dict[str, Dict[str, Set[str]]] = {}
    for _, row in std_df.iterrows():
        hsk = normalize_code(row.get(COL_HS_CODE, ""))
        if len(hsk) != 10:
            continue
        bucket = std_by_hsk.setdefault(
            hsk,
            {"standard_names": set(), "required_specs": set(), "detail_notes": set()},
        )
        push_limited(bucket["standard_names"], normalize_text(row.get(COL_STANDARD_NAME, "")))
        push_limited(bucket["required_specs"], normalize_text(row.get(COL_REQUIRED_SPECS, "")))
        push_limited(bucket["detail_notes"], normalize_text(row.get(COL_DETAIL_NOTES, "")))

    catalog: List[Dict[str, str]] = []
    for _, row in hs_df.iterrows():
        hsk = normalize_code(row.get(COL_HS_CODE, ""))
        if len(hsk) != 10:
            continue

        ko = normalize_text(row.get(COL_KO_NAME, ""))
        en = normalize_text(row.get(COL_EN_NAME, ""))
        if not ko and not en:
            continue

        std = std_by_hsk.get(hsk, {"standard_names": set(), "required_specs": set(), "detail_notes": set()})
        standard_names = " | ".join(sorted(std["standard_names"]))
        required_specs = " | ".join(sorted(std["required_specs"]))
        detail_notes = " | ".join(sorted(std["detail_notes"]))

        catalog.append(
            {
                "hsk": hsk,
                "hs6": hsk[:6],
                "ko_name": ko,
                "en_name": en,
                "start_date": normalize_date(row.get(COL_START_DATE, "")),
                "end_date": normalize_date(row.get(COL_END_DATE, "")),
                "weight_unit": normalize_text(row.get(COL_WEIGHT_UNIT, "")),
                "nature_code_name": normalize_nature_name(row.get(COL_NATURE_CODE_NAME, "")),
                "standard_names": standard_names,
                "required_specs": required_specs,
                "detail_notes": detail_notes,
            }
        )

    catalog.sort(key=lambda item: item["hsk"])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(catalog, ensure_ascii=False, separators=(",", ":"))
    ts_content = (
        "// Generated by scripts/build_hs_catalog.py. Do not edit by hand.\n"
        "export type HsCatalogRow = {\n"
        "  hsk: string;\n"
        "  hs6: string;\n"
        "  ko_name: string;\n"
        "  en_name: string;\n"
        "  start_date: string;\n"
        "  end_date: string;\n"
        "  weight_unit: string;\n"
        "  nature_code_name: string;\n"
        "  standard_names: string;\n"
        "  required_specs: string;\n"
        "  detail_notes: string;\n"
        "};\n\n"
        f"export const HS_CATALOG: HsCatalogRow[] = {payload};\n"
    )
    out_path.write_text(ts_content, encoding="utf-8")
    print(f"Wrote {len(catalog)} rows to {out_path}")


if __name__ == "__main__":
    main()
